name: Lint
on:
  workflow_dispatch

name: Lint Check and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8  # Install pylint, flake8, and any other dependencies

      - name: Run Pylint
        id: pylint
        run: |
          pylint_score=$(pylint src/ye3sld/ye3sld.py | tee pylint_report.txt | grep 'Your code has been rated at' | awk '{print $7}')
          echo "Pylint score: $pylint_score"
          echo "::set-output name=pylint_score::$pylint_score"

      - name: Run Flake8
        id: flake8
        run: |
          flake8 src/ye3sld/ye3sld.py > flake8_report.txt || true
          flake8_errors=$(cat flake8_report.txt | wc -l)
          echo "Flake8 errors: $flake8_errors"
          echo "::set-output name=flake8_errors::$flake8_errors"
