
name: Test

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Run Python script
        env:
          URL: "${{ secrets.URL }}"
          ID: "${{ secrets.ID }}"
          SECRET: "${{ secrets.SECRET }}"
          BASE: "${{ secrets.BASE }}"
          ARGUMENTS: "${{ vars.ARGUMENTS }}"
        run: python -m unittest discover -s tests -p "*.py"
